sudo: true
dist: xenial

jobs:
  include:
    - stage: build docker image
      if: tag IS present
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t humanoo .
      - docker images
      - docker tag humanoo $DOCKER_USERNAME/humanoo
      - docker push $DOCKER_USERNAME/humanoo
    - stage: test
      script:
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer install
      - docker run -v `pwd`:/app -ti --rm php:7.2 /app/vendor/bin/phpunit /app/tests